const data = [
    {id: 1, title: `Harry Potter and the Sorcerer's Stone`, author: "J.K. Rowling", release: '1997', content: `Till now there's been no magic for Harry Potter. He lives with the miserable Dursleys and their abominable son, Dudley. Harry’s room is a tiny closet at the foot of the stairs, and he hasn’t had a birthday party in eleven years. But then a mysterious letter arrives by owl messenger: a letter with an invitation to an incredible place called the Hogwarts School of Witchcraft and Wizardry. And there he finds not only friends, flying sports on broomsticks, and magic in everything from classes to meals, but a great destiny that’s been waiting for him . . . if Harry can survive the encounter.`},
    {id: 2, title: `Harry Potter and the Chamber of Secrets`, author: "J.K. Rowling", release: '1998', content: `Harry’s second year at Hogwarts is rife with fresh torments and horrors, including an outrageously stuck-up new professor, Gilderoy Lockhart, a spirit named Moaning Myrtle who haunts the girls’ bathroom, and the unwanted attentions of Ron Weasley’s younger sister, Ginny. But these seem minor when the real trouble begins, and someone — or something — starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally revealed? Or could it be the one everyone at Hogwarts most suspects . . . Harry Potter himself!`},
    {id: 3, title: `Harry Potter and the Prisoner of Azkaban`, author: "J.K. Rowling", release: '1999', content: `For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be a dedicated follower of the Dark Lord, Voldemort. Now he’s escaped. And the Azkaban guards heard Black muttering in his sleep, “He’s at Hogwarts . . . he’s at Hogwarts.” Is he coming for Harry? Harry Potter isn’t safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may be a traitor in their midst.`},
    {id: 4, title: `Harry Potter and the Goblet of Fire`, author: "J.K. Rowling", release: '2000', content: `Harry Potter wants to get away from the pernicious Dursleys and go to the Quidditch World Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event involving two other rival schools of magic, and a competition that hasn’t happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. Unfortunately for Harry Potter, he’s not normal; he’s different — even by Wizarding standards. And in his case, different can be deadly.`},
    {id: 5, title: `Harry Potter and the Order of the Phoenix`, author: "J.K. Rowling", release: '2003', content: `The rebellion begins! Lord Voldemort has returned, but the Ministry of Magic is doing everything it can to keep the wizarding world from knowing the truth – including appointing Ministry official Dolores Umbridge as the new Defence Against the Dark Arts professor at Hogwarts. When Umbridge refuses to teach practical defensive magic, Ron and Hermione convince Harry to secretly train a select group of students for the wizarding war that lies ahead. A terrifying showdown between good and evil awaits in this enthralling film version of the fifth novel in J.K. Rowling’s Harry Potter series. Prepare for battle!`},
    {id: 6, title: `Harry Potter and the Half-Blood Prince`, author: "J.K. Rowling", release: '2005', content: `The war against Voldemort is not going well. Hermione scans the pages of the Daily Prophet, reading out terrible news. Dumbledore is absent from Hogwarts for long stretches of time, and yet . . . As in all wars, life goes on. Sixth-year students learn to Apparate — and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are tough, though Harry receives some extraordinary help from the mysterious Half-Blood Prince. And all the while Harry searches for the full and complex story of the boy who became Lord Voldemort — hoping to find what may be his only vulnerability.`},
    {id: 7, title: `Harry Potter and the Deathly Hallows`, author: "J.K. Rowling", release: '2007', content: `It's no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it's up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry's Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death.`},
]

const list = () => {
    return [...data]
}

const find = (id) => {
    const post = data.find(post => post.id === +id);
    return {...post}
}

module.exports = {list: list, find: find}